version: '3.9'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
      
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: wishtchdev
      MONGO_INITDB_ROOT_PASSWORD: wishtchdev

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
       - "8081:8081"
    networks:
      - default
    volumes:
      - data:/data
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://wishtchdev:wishtchdev@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: wishtchdev
      ME_CONFIG_MONGODB_ADMINPASSWORD: wishtchdev
      ME_CONFIG_MONGODB_AUTH_USERNAME: wishtchdev
      ME_CONFIG_MONGODB_AUTH_PASSWORD: wishtchdev

networks:
  default:
    name: docker_mongo_express_network
    driver: bridge

volumes:
  data:
    name: docker_mongo_express_data
    driver: local